diesel::table! {
    articles (id) {
        id -> Unsigned<Integer>,
        status -> Unsigned<TinyInt>,
        created -> Unsigned<Integer>,
        updated -> Unsigned<Integer>,
        sub_title -> Nullable<Varchar>,
        img_wide -> Nullable<Varchar>,
        img_top -> Nullable<Varchar>,
        is_main -> Nullable<Unsigned<TinyInt>>,
        announcement_main -> Nullable<Varchar>,
        img_main -> Nullable<Varchar>,
        is_black -> Nullable<Unsigned<TinyInt>>,
        lj_id -> Nullable<Unsigned<Integer>>,
        title -> Nullable<Varchar>,
        announcement -> Nullable<Text>,
        description -> Nullable<Text>,
        tags -> Nullable<Binary>,
        uid -> Nullable<Unsigned<Integer>>,
        views -> Nullable<Unsigned<Integer>>,
        hash -> Nullable<Varchar>,
        comment_access -> Nullable<Unsigned<TinyInt>>,
        ccount -> Nullable<Unsigned<Integer>>,
        pub_date -> Nullable<Unsigned<Integer>>,
        rate -> Nullable<Unsigned<Integer>>,
        rate_positive -> Nullable<Unsigned<Integer>>,
        rate_negative -> Nullable<Unsigned<Integer>>,
        rated_list -> Nullable<Binary>,
    }
}
